apiVersion: apps/v1
kind: Deployment
metadata:
  name: chains-student
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chains-student
  template:
    metadata:
      labels:
        app: chains-student
    spec:
      containers:
        - name: chains-student
          image: durczokj/chains-student:__IMAGE_TAG__
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Host
                  value: chains-student.durczok.ovh
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
              httpHeaders:
                - name: Host
                  value: chains-student.durczok.ovh
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests: { cpu: 10m, memory: 16Mi }
            limits:   { cpu: 100m, memory: 64Mi }
